---

name: trove CI

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  QuickFormat:
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout-action
        uses: actions/checkout@v3
      - name: dprint-check-action
        uses: dprint/check@v2.2

  cargo-fmt-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'clippy linter'
        run: cargo clippy --release && cd trove-internal && cargo +stable clippy --target x86_64-unknown-linux-gnu
      - name: 'Check formatting'
        run: cargo fmt --check && cd trove-internal && cargo fmt --check

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Run trove-internal tests'
        run: cd trove-internal && cargo +stable test --target x86_64-unknown-linux-gnu

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Install Dependencies'
        run: sudo apt-get update
      - name: 'Build firmware'
        run: cargo build --release
